# Generated by Django 5.2.7 on 2025-12-29 18:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('flag_image', models.ImageField(upload_to='flags/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrammarTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=2)),
                ('order', models.IntegerField()),
                ('description', models.TextField()),
                ('language', models.ForeignKey(help_text='Target language (English, German, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='grammar_topics', to='lms.language')),
            ],
            options={
                'ordering': ['language', 'cefr_level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GrammarLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('explanation', models.TextField(help_text="Grammar rule explanation in user's native language")),
                ('examples', models.JSONField(default=list, help_text='[{"target": "I am learning", "native": "Men o\'rganyapman"}]')),
                ('order', models.IntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_lessons', to='lms.grammartopic')),
                ('explanation_lang', models.ForeignKey(help_text="Language of explanation (usually user's native language)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grammar_lessons', to='lms.language')),
            ],
            options={
                'ordering': ['topic', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cefr_level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], help_text='CEFR level this book covers', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='lms.language')),
            ],
            options={
                'ordering': ['language', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LanguagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('from_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_pairs_from', to='lms.language')),
                ('target_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_pairs_target', to='lms.language')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('difficulty', models.IntegerField(default=1)),
                ('order', models.IntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('language_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='lms.languagepair')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('practice', 'Practice'), ('story', 'Story'), ('review', 'Unit Review')], default='vocabulary', max_length=20)),
                ('total_stars', models.IntegerField(default=5)),
                ('xp_reward', models.IntegerField(default=10)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grammar_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.grammartopic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('translate', 'Translate this sentence'), ('fill_blank', 'Fill in the blank'), ('listen_type', 'Type what you hear'), ('speak', 'Speak this sentence'), ('match_pairs', 'Match pairs'), ('select_word', 'Select the correct word'), ('grammar_correct_form', 'Choose correct form'), ('grammar_rewrite', 'Rewrite sentence'), ('grammar_find_error', 'Find the error')], max_length=50)),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prompt', models.TextField(help_text='Question text or prompt')),
                ('correct_answer', models.TextField(help_text='Correct answer')),
                ('explanation', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammar_lesson', models.ForeignKey(blank=True, help_text='Grammar lesson being tested', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.grammarlesson')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.lesson')),
            ],
            options={
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('time_spent_sec', models.IntegerField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('review_interval_days', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='lms.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='lms.question')),
            ],
            options={
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Unit number 1-30', validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='lms.book')),
                ('lang_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='lms.languagepair')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.unit'),
        ),
        migrations.AddField(
            model_name='grammarlesson',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grammar_lessons', to='lms.unit'),
        ),
        migrations.CreateModel(
            name='UserLanguagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cefr_level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'Elementary'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], default='A1', max_length=20)),
                ('level_progress_percent', models.IntegerField(default=0, help_text='Progress % within current CEFR level', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completed_levels', models.JSONField(default=list, help_text='["A1", "A2"] - list of completed CEFR levels')),
                ('assessment_score', models.IntegerField(blank=True, null=True)),
                ('total_words_learned', models.IntegerField(default=0)),
                ('total_grammar_topics', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('curr_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_practice_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curr_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.unit')),
                ('lang_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_language_pairs', to='lms.languagepair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_language_pairs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('determined_level', models.CharField(max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to=settings.AUTH_USER_MODEL)),
                ('user_lang_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='lms.userlanguagepair')),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('current', 'Current'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('stars_earned', models.IntegerField(default=0)),
                ('questions_completed', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('word_number', models.IntegerField(help_text='Word position in unit (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('audio', models.FileField(blank=True, help_text='Pronunciation audio', null=True, upload_to='vocabulary/audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vocabulary/images/')),
                ('example_sentence', models.TextField(blank=True)),
                ('part_of_speech', models.CharField(choices=[('noun', 'Noun'), ('pronoun', 'Pronoun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('interjection', 'Interjection'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='lms.unit')),
            ],
            options={
                'ordering': ['unit', 'word_number'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='vocabulary',
            field=models.ForeignKey(blank=True, help_text='Vocabulary word being tested', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.vocabulary'),
        ),
        migrations.CreateModel(
            name='VocabularyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=200)),
                ('example_translation', models.TextField(blank=True, help_text='Translated example sentence')),
                ('language', models.ForeignKey(help_text='Language of this translation', on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_translations', to='lms.language')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_translations', to='lms.vocabulary')),
            ],
        ),
        migrations.AddIndex(
            model_name='grammartopic',
            index=models.Index(fields=['language', 'cefr_level', 'order'], name='lms_grammar_languag_ec4fa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grammartopic',
            unique_together={('language', 'cefr_level', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='languagepair',
            unique_together={('from_lang', 'target_lang')},
        ),
        migrations.AlterUniqueTogether(
            name='questionoption',
            unique_together={('question', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('book', 'lang_pair', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('unit', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='userlanguagepair',
            unique_together={('user', 'lang_pair')},
        ),
        migrations.AlterUniqueTogether(
            name='userlessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='vocabulary',
            unique_together={('unit', 'word_number')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('lesson', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='vocabularytranslation',
            unique_together={('vocabulary', 'language')},
        ),
    ]
