# Generated by Django 5.2.7 on 2025-12-30 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('translate', 'Translate'), ('fill_blank', 'Fill in the blank'), ('select_word', 'Select word'), ('listen_type', 'Listen and type'), ('speak', 'Speak'), ('match_pairs', 'Match pairs'), ('grammar_correct_form', 'Choose correct form'), ('grammar_rewrite', 'Rewrite sentence'), ('grammar_find_error', 'Find error')], max_length=30)),
                ('instruction_text', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_instructions', to='lms.language')),
            ],
            options={
                'unique_together': {('question_type', 'language')},
            },
        ),
    ]
